services:

  db:
    image: mysql:8.3.0
    ports:
      - 3307:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hackathon

#  spring-boot-app:
#    build: .
#    ports:
#      - "8081:8081"
#    depends_on:
#      - db